version: '3'
services:
  web:
    image: php:7.4-apache
    volumes:
      - .:/var/www/html
    ports:
      - 8080:80
  db:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./db-init:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=${POSTGRES_USER}
      - PMA_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 8081:80
volumes:
  postgres_data:
